name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Semantic Release
        uses: digitalservicebund/semantic-release-action@44c10ccaba96446fee0f174c5b944fa517eb217c # v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
